print("Desafio 22")
nome=input("Digite o seu nome completo: ")#.strip()
completo=nome.upper()
completo2=nome.lower()
#nome2=nome.strip()
print(completo)
print(completo2)
#print("Seu nome tem ao todo {} letras ".format(len(nome2)))
print("Seu nome tem ao todo {} letras.".format(len(nome)-nome.count(' ')))
print("Seu primeiro nome tem {} letras ".format(nome.find(' ')))
