##print("Digito de um numero: ")
num=input("Digite um numero: ")
print("Unidade {} " .format(num[3]))
print("dezena {} " .format(num[2]))
print("centena {} " .format(num[1]))
print("milhar {} " .format(num[0]))
